-- EAGV trainer module schema patch
-- Safe to rerun: creates missing tables, constraints, columns and indexes without dropping existing structures.
-- Compatibility notes:
--   * members.id already uses UUID in the current schema.
--   * users.id already uses INTEGER in the current schema, so trainer/user foreign keys keep INTEGER.
--   * physical_assessments already exists with INTEGER primary key; this script extends it instead of replacing it.
--   * UUID primary keys in new tables are designed to be generated by the application layer
--     (Prisma, EF Core, .NET APIs, FastAPI), avoiding a hard dependency on database UUID extensions.

BEGIN;

-- ---------------------------------------------------------------------------
-- ROOT TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.trainer_profiles (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL,
    specialty VARCHAR(120),
    cref_registration VARCHAR(80),
    bio TEXT,
    experience_years INTEGER,
    instagram_url TEXT,
    profile_photo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS specialty VARCHAR(120);
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS cref_registration VARCHAR(80);
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS experience_years INTEGER;
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS instagram_url TEXT;
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS profile_photo_url TEXT;
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.trainer_profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_trainer_profiles_user'
          AND conrelid = 'public.trainer_profiles'::regclass
    ) THEN
        ALTER TABLE public.trainer_profiles
            ADD CONSTRAINT fk_trainer_profiles_user
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_trainer_profiles_user_id
    ON public.trainer_profiles (user_id);

COMMENT ON TABLE public.trainer_profiles IS 'Profile metadata for personal trainers linked to system users.';
COMMENT ON COLUMN public.trainer_profiles.user_id IS 'FK to users(id); users.id is INTEGER in the current schema.';

CREATE TABLE IF NOT EXISTS public.exercise_library (
    id UUID PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    muscle_group VARCHAR(120),
    exercise_type VARCHAR(80),
    equipment VARCHAR(120),
    difficulty_level VARCHAR(80),
    instructions TEXT,
    video_url TEXT,
    image_url TEXT,
    created_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS name VARCHAR(160);
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS muscle_group VARCHAR(120);
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS exercise_type VARCHAR(80);
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS equipment VARCHAR(120);
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR(80);
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.exercise_library ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_exercise_library_created_by'
          AND conrelid = 'public.exercise_library'::regclass
    ) THEN
        ALTER TABLE public.exercise_library
            ADD CONSTRAINT fk_exercise_library_created_by
            FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_exercise_library_name
    ON public.exercise_library (name);

CREATE INDEX IF NOT EXISTS ix_exercise_library_muscle_group
    ON public.exercise_library (muscle_group);

CREATE INDEX IF NOT EXISTS ix_exercise_library_exercise_type
    ON public.exercise_library (exercise_type);

COMMENT ON TABLE public.exercise_library IS 'Reusable exercise catalog for trainer workflows, mobile sync and AI recommendations.';
COMMENT ON COLUMN public.exercise_library.instructions IS 'Free-text instructions designed to support trainer notes and future AI assistance.';

-- ---------------------------------------------------------------------------
-- MEMBER/TRAINER ROOT RELATIONSHIPS
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.workout_plans (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL,
    trainer_id INTEGER NOT NULL,
    title VARCHAR(160),
    objective TEXT,
    difficulty_level VARCHAR(80),
    status VARCHAR(50),
    start_date DATE,
    end_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS trainer_id INTEGER;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS title VARCHAR(160);
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR(80);
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_plans_member'
          AND conrelid = 'public.workout_plans'::regclass
    ) THEN
        ALTER TABLE public.workout_plans
            ADD CONSTRAINT fk_workout_plans_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_plans_trainer'
          AND conrelid = 'public.workout_plans'::regclass
    ) THEN
        ALTER TABLE public.workout_plans
            ADD CONSTRAINT fk_workout_plans_trainer
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_workout_plans_member_id
    ON public.workout_plans (member_id);

CREATE INDEX IF NOT EXISTS ix_workout_plans_trainer_id
    ON public.workout_plans (trainer_id);

CREATE INDEX IF NOT EXISTS ix_workout_plans_status
    ON public.workout_plans (status);

CREATE TABLE IF NOT EXISTS public.trainer_notes (
    id UUID PRIMARY KEY,
    trainer_id INTEGER NOT NULL,
    member_id UUID NOT NULL,
    note_type VARCHAR(80),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS trainer_id INTEGER;
ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS note_type VARCHAR(80);
ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.trainer_notes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_trainer_notes_trainer'
          AND conrelid = 'public.trainer_notes'::regclass
    ) THEN
        ALTER TABLE public.trainer_notes
            ADD CONSTRAINT fk_trainer_notes_trainer
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_trainer_notes_member'
          AND conrelid = 'public.trainer_notes'::regclass
    ) THEN
        ALTER TABLE public.trainer_notes
            ADD CONSTRAINT fk_trainer_notes_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_trainer_notes_member_id
    ON public.trainer_notes (member_id);

CREATE INDEX IF NOT EXISTS ix_trainer_notes_trainer_id
    ON public.trainer_notes (trainer_id);

CREATE TABLE IF NOT EXISTS public.training_goals (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL,
    trainer_id INTEGER NOT NULL,
    goal_type VARCHAR(80),
    target_value NUMERIC(10, 2),
    current_value NUMERIC(10, 2),
    target_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS trainer_id INTEGER;
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS goal_type VARCHAR(80);
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS target_value NUMERIC(10, 2);
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS current_value NUMERIC(10, 2);
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS target_date DATE;
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.training_goals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_goals_member'
          AND conrelid = 'public.training_goals'::regclass
    ) THEN
        ALTER TABLE public.training_goals
            ADD CONSTRAINT fk_training_goals_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_goals_trainer'
          AND conrelid = 'public.training_goals'::regclass
    ) THEN
        ALTER TABLE public.training_goals
            ADD CONSTRAINT fk_training_goals_trainer
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_training_goals_member_id
    ON public.training_goals (member_id);

CREATE INDEX IF NOT EXISTS ix_training_goals_trainer_id
    ON public.training_goals (trainer_id);

CREATE TABLE IF NOT EXISTS public.training_sessions (
    id UUID PRIMARY KEY,
    trainer_id INTEGER NOT NULL,
    member_id UUID NOT NULL,
    scheduled_start TIMESTAMPTZ NOT NULL,
    scheduled_end TIMESTAMPTZ,
    session_type VARCHAR(80),
    location VARCHAR(160),
    notes TEXT,
    status VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS trainer_id INTEGER;
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS scheduled_start TIMESTAMPTZ;
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS scheduled_end TIMESTAMPTZ;
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS session_type VARCHAR(80);
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS location VARCHAR(160);
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.training_sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_sessions_trainer'
          AND conrelid = 'public.training_sessions'::regclass
    ) THEN
        ALTER TABLE public.training_sessions
            ADD CONSTRAINT fk_training_sessions_trainer
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_sessions_member'
          AND conrelid = 'public.training_sessions'::regclass
    ) THEN
        ALTER TABLE public.training_sessions
            ADD CONSTRAINT fk_training_sessions_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_training_sessions_member_id
    ON public.training_sessions (member_id);

CREATE INDEX IF NOT EXISTS ix_training_sessions_trainer_id
    ON public.training_sessions (trainer_id);

CREATE INDEX IF NOT EXISTS ix_training_sessions_scheduled_start
    ON public.training_sessions (scheduled_start);

CREATE INDEX IF NOT EXISTS ix_training_sessions_trainer_start
    ON public.training_sessions (trainer_id, scheduled_start);

COMMENT ON TABLE public.training_sessions IS 'Trainer session schedule optimized for calendar APIs, mobile sync and attendance workflows.';

CREATE TABLE IF NOT EXISTS public.training_attendance (
    id UUID PRIMARY KEY,
    training_session_id UUID NOT NULL,
    member_id UUID NOT NULL,
    attendance_status VARCHAR(40),
    check_in_time TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS training_session_id UUID;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS attendance_status VARCHAR(40);
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS check_in_time TIMESTAMPTZ;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_attendance_session'
          AND conrelid = 'public.training_attendance'::regclass
    ) THEN
        ALTER TABLE public.training_attendance
            ADD CONSTRAINT fk_training_attendance_session
            FOREIGN KEY (training_session_id) REFERENCES public.training_sessions(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_training_attendance_member'
          AND conrelid = 'public.training_attendance'::regclass
    ) THEN
        ALTER TABLE public.training_attendance
            ADD CONSTRAINT fk_training_attendance_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_training_attendance_member_id
    ON public.training_attendance (member_id);

CREATE INDEX IF NOT EXISTS ix_training_attendance_session_id
    ON public.training_attendance (training_session_id);

-- ---------------------------------------------------------------------------
-- EXISTING TABLE ADAPTATION: physical_assessments
-- ---------------------------------------------------------------------------

ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS trainer_id INTEGER;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS body_measurement_id UUID;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS posture_analysis TEXT;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS mobility_score NUMERIC(6, 2);
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS cardio_conditioning TEXT;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS injury_history TEXT;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS limitations TEXT;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS recommendations TEXT;
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS assessment_date TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.physical_assessments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

UPDATE public.physical_assessments
SET posture_analysis = COALESCE(posture_analysis, posture_notes)
WHERE posture_analysis IS NULL AND posture_notes IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_physical_assessments_trainer'
          AND conrelid = 'public.physical_assessments'::regclass
    ) THEN
        ALTER TABLE public.physical_assessments
            ADD CONSTRAINT fk_physical_assessments_trainer
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_physical_assessments_body_measurement'
          AND conrelid = 'public.physical_assessments'::regclass
    ) THEN
        ALTER TABLE public.physical_assessments
            ADD CONSTRAINT fk_physical_assessments_body_measurement
            FOREIGN KEY (body_measurement_id) REFERENCES public.body_measurements(id) ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_physical_assessments_trainer_id
    ON public.physical_assessments (trainer_id);

CREATE INDEX IF NOT EXISTS ix_physical_assessments_assessment_date
    ON public.physical_assessments (assessment_date);

COMMENT ON TABLE public.physical_assessments IS 'Existing table extended for trainer workflows without breaking the current integer primary key.';
COMMENT ON COLUMN public.physical_assessments.posture_analysis IS 'Preferred API field; posture_notes remains available for backward compatibility.';

-- ---------------------------------------------------------------------------
-- PLAN STRUCTURE TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.workout_days (
    id UUID PRIMARY KEY,
    workout_plan_id UUID NOT NULL,
    day_name VARCHAR(40),
    focus_area VARCHAR(120),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS workout_plan_id UUID;
ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS day_name VARCHAR(40);
ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS focus_area VARCHAR(120);
ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.workout_days ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_days_plan'
          AND conrelid = 'public.workout_days'::regclass
    ) THEN
        ALTER TABLE public.workout_days
            ADD CONSTRAINT fk_workout_days_plan
            FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_workout_days_workout_plan_id
    ON public.workout_days (workout_plan_id);

CREATE TABLE IF NOT EXISTS public.workout_periodization (
    id UUID PRIMARY KEY,
    workout_plan_id UUID NOT NULL,
    phase_name VARCHAR(120),
    objective TEXT,
    start_date DATE,
    end_date DATE,
    intensity_level VARCHAR(80),
    volume_level VARCHAR(80),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS workout_plan_id UUID;
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS phase_name VARCHAR(120);
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS intensity_level VARCHAR(80);
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS volume_level VARCHAR(80);
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.workout_periodization ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_periodization_plan'
          AND conrelid = 'public.workout_periodization'::regclass
    ) THEN
        ALTER TABLE public.workout_periodization
            ADD CONSTRAINT fk_workout_periodization_plan
            FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_workout_periodization_workout_plan_id
    ON public.workout_periodization (workout_plan_id);

CREATE TABLE IF NOT EXISTS public.workout_exercises (
    id UUID PRIMARY KEY,
    workout_day_id UUID NOT NULL,
    exercise_id UUID NOT NULL,
    exercise_order INTEGER,
    sets INTEGER,
    reps VARCHAR(80),
    rest_seconds INTEGER,
    tempo VARCHAR(40),
    load_kg NUMERIC(10, 2),
    duration_minutes INTEGER,
    observation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS workout_day_id UUID;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS exercise_id UUID;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS exercise_order INTEGER;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS sets INTEGER;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS reps VARCHAR(80);
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS rest_seconds INTEGER;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS tempo VARCHAR(40);
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS load_kg NUMERIC(10, 2);
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS duration_minutes INTEGER;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS observation TEXT;
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.workout_exercises ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_exercises_day'
          AND conrelid = 'public.workout_exercises'::regclass
    ) THEN
        ALTER TABLE public.workout_exercises
            ADD CONSTRAINT fk_workout_exercises_day
            FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_workout_exercises_exercise'
          AND conrelid = 'public.workout_exercises'::regclass
    ) THEN
        ALTER TABLE public.workout_exercises
            ADD CONSTRAINT fk_workout_exercises_exercise
            FOREIGN KEY (exercise_id) REFERENCES public.exercise_library(id) ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_workout_exercises_exercise_id
    ON public.workout_exercises (exercise_id);

CREATE INDEX IF NOT EXISTS ix_workout_exercises_day_id
    ON public.workout_exercises (workout_day_id);

CREATE INDEX IF NOT EXISTS ix_workout_exercises_day_order
    ON public.workout_exercises (workout_day_id, exercise_order);

COMMENT ON TABLE public.workout_exercises IS 'Exercise prescriptions structured for workout rendering, mobile offline sync and recommendation engines.';

-- ---------------------------------------------------------------------------
-- HISTORY / PROGRESS TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.member_workout_history (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL,
    workout_plan_id UUID NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_minutes INTEGER,
    calories_burned NUMERIC(10, 2),
    perceived_effort VARCHAR(80),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS workout_plan_id UUID;
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS duration_minutes INTEGER;
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS calories_burned NUMERIC(10, 2);
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS perceived_effort VARCHAR(80);
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.member_workout_history ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_member_workout_history_member'
          AND conrelid = 'public.member_workout_history'::regclass
    ) THEN
        ALTER TABLE public.member_workout_history
            ADD CONSTRAINT fk_member_workout_history_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_member_workout_history_plan'
          AND conrelid = 'public.member_workout_history'::regclass
    ) THEN
        ALTER TABLE public.member_workout_history
            ADD CONSTRAINT fk_member_workout_history_plan
            FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_member_workout_history_member_id
    ON public.member_workout_history (member_id);

CREATE INDEX IF NOT EXISTS ix_member_workout_history_workout_plan_id
    ON public.member_workout_history (workout_plan_id);

CREATE INDEX IF NOT EXISTS ix_member_workout_history_completed_at
    ON public.member_workout_history (completed_at DESC);

CREATE TABLE IF NOT EXISTS public.exercise_progress (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL,
    exercise_id UUID NOT NULL,
    max_weight NUMERIC(10, 2),
    repetitions INTEGER,
    execution_notes TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS exercise_id UUID;
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS max_weight NUMERIC(10, 2);
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS repetitions INTEGER;
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS execution_notes TEXT;
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.exercise_progress ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_exercise_progress_member'
          AND conrelid = 'public.exercise_progress'::regclass
    ) THEN
        ALTER TABLE public.exercise_progress
            ADD CONSTRAINT fk_exercise_progress_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_exercise_progress_exercise'
          AND conrelid = 'public.exercise_progress'::regclass
    ) THEN
        ALTER TABLE public.exercise_progress
            ADD CONSTRAINT fk_exercise_progress_exercise
            FOREIGN KEY (exercise_id) REFERENCES public.exercise_library(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_exercise_progress_member_id
    ON public.exercise_progress (member_id);

CREATE INDEX IF NOT EXISTS ix_exercise_progress_exercise_id
    ON public.exercise_progress (exercise_id);

CREATE INDEX IF NOT EXISTS ix_exercise_progress_recorded_at
    ON public.exercise_progress (recorded_at DESC);

CREATE INDEX IF NOT EXISTS ix_exercise_progress_member_exercise_recorded
    ON public.exercise_progress (member_id, exercise_id, recorded_at DESC);

COMMENT ON TABLE public.exercise_progress IS 'Performance snapshots intended for progress charts, mobile sync and AI training suggestions.';

COMMIT;