-- EAGV nutrition module schema patch
-- Safe to rerun: creates missing tables, columns, constraints and indexes without dropping existing structures.
-- Compatibility notes:
--   * members(id) already uses UUID in this schema and is referenced as UUID.
--   * users(id) already uses INTEGER in this schema, so user-facing foreign keys keep INTEGER to avoid breaking compatibility.
--   * UUID primary keys in the new nutrition tables are intended to be generated by the API/ORM layer
--     (Prisma, EF Core, .NET APIs, FastAPI), avoiding a hard dependency on database UUID extensions.
--   * body_measurements and body_photos already exist and are only extended with missing fields/indexes.

BEGIN;

-- ---------------------------------------------------------------------------
-- ROOT TABLE: nutrition_profiles
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.nutrition_profiles (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL,
    nutritionist_id INTEGER NOT NULL,
    basal_metabolic_rate NUMERIC(10, 2),
    daily_calorie_target NUMERIC(10, 2),
    water_intake_goal NUMERIC(10, 2),
    activity_level VARCHAR(80),
    sleep_hours NUMERIC(5, 2),
    stress_level VARCHAR(80),
    primary_goal VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS nutritionist_id INTEGER;
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS basal_metabolic_rate NUMERIC(10, 2);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS daily_calorie_target NUMERIC(10, 2);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS water_intake_goal NUMERIC(10, 2);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS activity_level VARCHAR(80);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS sleep_hours NUMERIC(5, 2);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS stress_level VARCHAR(80);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS primary_goal VARCHAR(120);
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.nutrition_profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_nutrition_profiles_member'
          AND conrelid = 'public.nutrition_profiles'::regclass
    ) THEN
        ALTER TABLE public.nutrition_profiles
            ADD CONSTRAINT fk_nutrition_profiles_member
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_nutrition_profiles_nutritionist'
          AND conrelid = 'public.nutrition_profiles'::regclass
    ) THEN
        ALTER TABLE public.nutrition_profiles
            ADD CONSTRAINT fk_nutrition_profiles_nutritionist
            FOREIGN KEY (nutritionist_id) REFERENCES public.users(id) ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_nutrition_profiles_member_id
    ON public.nutrition_profiles (member_id);

CREATE INDEX IF NOT EXISTS ix_nutrition_profiles_nutritionist_id
    ON public.nutrition_profiles (nutritionist_id);

COMMENT ON TABLE public.nutrition_profiles IS 'Root entity for nutrition workflows linked to members and nutritionists.';
COMMENT ON COLUMN public.nutrition_profiles.member_id IS 'FK to members(id).';
COMMENT ON COLUMN public.nutrition_profiles.nutritionist_id IS 'FK to users(id); users.id is INTEGER in the current schema.';

-- ---------------------------------------------------------------------------
-- DEPENDENT TABLES BY nutrition_profile_id
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.nutrition_anamnesis (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    meals_per_day INTEGER,
    alcohol_consumption VARCHAR(80),
    smoking BOOLEAN,
    water_intake NUMERIC(10, 2),
    digestive_issues TEXT,
    food_cravings TEXT,
    wake_up_time TIME,
    sleep_time TIME,
    work_routine TEXT,
    previous_diets TEXT,
    eating_disorders_history TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS meals_per_day INTEGER;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS alcohol_consumption VARCHAR(80);
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS smoking BOOLEAN;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS water_intake NUMERIC(10, 2);
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS digestive_issues TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS food_cravings TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS wake_up_time TIME;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS sleep_time TIME;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS work_routine TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS previous_diets TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS eating_disorders_history TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.nutrition_anamnesis ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_nutrition_anamnesis_profile'
          AND conrelid = 'public.nutrition_anamnesis'::regclass
    ) THEN
        ALTER TABLE public.nutrition_anamnesis
            ADD CONSTRAINT fk_nutrition_anamnesis_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_nutrition_anamnesis_nutrition_profile_id
    ON public.nutrition_anamnesis (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.food_restrictions (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    restriction_type VARCHAR(120),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.food_restrictions ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.food_restrictions ADD COLUMN IF NOT EXISTS restriction_type VARCHAR(120);
ALTER TABLE public.food_restrictions ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.food_restrictions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_food_restrictions_profile'
          AND conrelid = 'public.food_restrictions'::regclass
    ) THEN
        ALTER TABLE public.food_restrictions
            ADD CONSTRAINT fk_food_restrictions_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_food_restrictions_nutrition_profile_id
    ON public.food_restrictions (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.nutrition_goals (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    goal_type VARCHAR(120),
    target_weight NUMERIC(10, 2),
    target_body_fat NUMERIC(5, 2),
    target_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS goal_type VARCHAR(120);
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS target_weight NUMERIC(10, 2);
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS target_body_fat NUMERIC(5, 2);
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS target_date DATE;
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE public.nutrition_goals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_nutrition_goals_profile'
          AND conrelid = 'public.nutrition_goals'::regclass
    ) THEN
        ALTER TABLE public.nutrition_goals
            ADD CONSTRAINT fk_nutrition_goals_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_nutrition_goals_nutrition_profile_id
    ON public.nutrition_goals (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.meal_plans (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    title VARCHAR(160),
    objective TEXT,
    calories NUMERIC(10, 2),
    start_date DATE,
    end_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS title VARCHAR(160);
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS calories NUMERIC(10, 2);
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_meal_plans_profile'
          AND conrelid = 'public.meal_plans'::regclass
    ) THEN
        ALTER TABLE public.meal_plans
            ADD CONSTRAINT fk_meal_plans_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_meal_plans_nutrition_profile_id
    ON public.meal_plans (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.supplements (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    supplement_name VARCHAR(160),
    dosage VARCHAR(120),
    frequency VARCHAR(120),
    objective TEXT,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS supplement_name VARCHAR(160);
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS dosage VARCHAR(120);
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS frequency VARCHAR(120);
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.supplements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_supplements_profile'
          AND conrelid = 'public.supplements'::regclass
    ) THEN
        ALTER TABLE public.supplements
            ADD CONSTRAINT fk_supplements_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_supplements_nutrition_profile_id
    ON public.supplements (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.lab_exams (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    exam_name VARCHAR(160),
    exam_date DATE,
    file_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS exam_name VARCHAR(160);
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS exam_date DATE;
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.lab_exams ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_lab_exams_profile'
          AND conrelid = 'public.lab_exams'::regclass
    ) THEN
        ALTER TABLE public.lab_exams
            ADD CONSTRAINT fk_lab_exams_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_lab_exams_nutrition_profile_id
    ON public.lab_exams (nutrition_profile_id);

CREATE TABLE IF NOT EXISTS public.nutrition_progress (
    id UUID PRIMARY KEY,
    nutrition_profile_id UUID NOT NULL,
    adherence_score NUMERIC(5, 2),
    energy_level VARCHAR(80),
    hunger_level VARCHAR(80),
    mood VARCHAR(80),
    notes TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS nutrition_profile_id UUID;
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS adherence_score NUMERIC(5, 2);
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS energy_level VARCHAR(80);
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS hunger_level VARCHAR(80);
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS mood VARCHAR(80);
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.nutrition_progress ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_nutrition_progress_profile'
          AND conrelid = 'public.nutrition_progress'::regclass
    ) THEN
        ALTER TABLE public.nutrition_progress
            ADD CONSTRAINT fk_nutrition_progress_profile
            FOREIGN KEY (nutrition_profile_id) REFERENCES public.nutrition_profiles(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_nutrition_progress_nutrition_profile_id
    ON public.nutrition_progress (nutrition_profile_id);

CREATE INDEX IF NOT EXISTS ix_nutrition_progress_recorded_at
    ON public.nutrition_progress (recorded_at DESC);

-- ---------------------------------------------------------------------------
-- MEMBERSHIP-LEVEL EXISTING TABLE EXTENSIONS
-- ---------------------------------------------------------------------------

ALTER TABLE public.body_measurements ADD COLUMN IF NOT EXISTS visceral_fat NUMERIC(6, 2);
ALTER TABLE public.body_measurements ADD COLUMN IF NOT EXISTS bmi NUMERIC(6, 2);
ALTER TABLE public.body_measurements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

CREATE INDEX IF NOT EXISTS ix_body_measurements_recorded_at
    ON public.body_measurements (recorded_at DESC);

COMMENT ON COLUMN public.body_measurements.created_by IS 'FK kept on users(id) because the existing schema does not use employees(id).';
COMMENT ON COLUMN public.body_measurements.visceral_fat IS 'Optional visceral fat metric for nutrition and body-composition monitoring.';
COMMENT ON COLUMN public.body_measurements.bmi IS 'Optional BMI snapshot persisted for reporting interoperability.';

ALTER TABLE public.body_photos ADD COLUMN IF NOT EXISTS front_photo_url TEXT;
ALTER TABLE public.body_photos ADD COLUMN IF NOT EXISTS side_photo_url TEXT;
ALTER TABLE public.body_photos ADD COLUMN IF NOT EXISTS back_photo_url TEXT;
ALTER TABLE public.body_photos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.body_photos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Preserve compatibility with the legacy single-photo model by mapping existing rows into the new URL columns.
UPDATE public.body_photos
SET front_photo_url = COALESCE(front_photo_url, image_url)
WHERE type = 'front' AND front_photo_url IS NULL;

UPDATE public.body_photos
SET side_photo_url = COALESCE(side_photo_url, image_url)
WHERE type = 'side' AND side_photo_url IS NULL;

UPDATE public.body_photos
SET back_photo_url = COALESCE(back_photo_url, image_url)
WHERE type = 'back' AND back_photo_url IS NULL;

COMMENT ON COLUMN public.body_photos.front_photo_url IS 'Grouped-photo API field; legacy image_url/type columns remain supported.';
COMMENT ON COLUMN public.body_photos.side_photo_url IS 'Grouped-photo API field; legacy image_url/type columns remain supported.';
COMMENT ON COLUMN public.body_photos.back_photo_url IS 'Grouped-photo API field; legacy image_url/type columns remain supported.';

-- ---------------------------------------------------------------------------
-- MEAL PLAN CHILD TABLES
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.meal_plan_meals (
    id UUID PRIMARY KEY,
    meal_plan_id UUID NOT NULL,
    meal_name VARCHAR(160),
    time TIME,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS meal_plan_id UUID;
ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS meal_name VARCHAR(160);
ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS time TIME;
ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.meal_plan_meals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_meal_plan_meals_plan'
          AND conrelid = 'public.meal_plan_meals'::regclass
    ) THEN
        ALTER TABLE public.meal_plan_meals
            ADD CONSTRAINT fk_meal_plan_meals_plan
            FOREIGN KEY (meal_plan_id) REFERENCES public.meal_plans(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_meal_plan_meals_meal_plan_id
    ON public.meal_plan_meals (meal_plan_id);

CREATE TABLE IF NOT EXISTS public.meal_foods (
    id UUID PRIMARY KEY,
    meal_id UUID NOT NULL,
    food_name VARCHAR(160),
    quantity NUMERIC(10, 2),
    unit VARCHAR(40),
    calories NUMERIC(10, 2),
    protein NUMERIC(10, 2),
    carbs NUMERIC(10, 2),
    fat NUMERIC(10, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS meal_id UUID;
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS food_name VARCHAR(160);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS quantity NUMERIC(10, 2);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS unit VARCHAR(40);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS calories NUMERIC(10, 2);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS protein NUMERIC(10, 2);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS carbs NUMERIC(10, 2);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS fat NUMERIC(10, 2);
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.meal_foods ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_meal_foods_meal'
          AND conrelid = 'public.meal_foods'::regclass
    ) THEN
        ALTER TABLE public.meal_foods
            ADD CONSTRAINT fk_meal_foods_meal
            FOREIGN KEY (meal_id) REFERENCES public.meal_plan_meals(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS ix_meal_foods_meal_id
    ON public.meal_foods (meal_id);

COMMIT;